### PR TITLE
Mute at Startup feature

### PR DESCRIPTION
**Pull request by dl1rf**
I have added a Checkbox to the Main Settings Menu to allow forcing all receivers to be muted at startup.
If uncheckt the receivers settings will be applied.
The stored Default Volume will be preserved and used if the receiver is unmuted manually.

### CODE REVIEW

**Comment by dl1rf** [comment]
In the mean time I made a change to one main worker thread to reduce the CPU load with the WinterHill.

CPU load with four times streaming the Beacon:
Screenshot 2024-04-30 114535

And after applying the change:
Screenshot 2024-04-30 114952

**Comment by tomvdb** [comment]
Hi Martin,

Thanks for all your contributions. I'm keen to test this one out, especially around the better handling of the buffers. 

Any reason you are combining symbol rate and modcod though on the properties? I'm not a fan of that change :p but keen to hear the reason.

Thanks again :)

73,
Tom

**Comment by dl1rf** [comment]
Hi Tom,

The changed thread handling I will retest today with a Minitiouner Express and USB interface.
I am not sure if it work correctly. I am not sure if I did a test mistake last time I tested this.
I do not have the device in house and need to drive to our club station for testing.

The only reason for combining symbol rate and mod code was to reduce the amount of lines used in the group box.

Tomorrow I will get the parts for the Pico Tuner and I will build this so I can do testing with WinterHill and PicoTuner soon.
For the PicoTuner I will have an Ethernet Pico and an USB pico for exchange and testing.

Hopefully we will see us on QO100 soon. I am waiting for the PA heatsink to arrive.

73, de Martin

**Comment by dl1rf** [comment]
The critical code change with the thread is working with FTDI interface too.
Screenshot 2024-05-02 182244

By the way, do you like the buttons coloring for Stream and Record button in the picture?
Are the indicator circles a "shall" for OpenTuner?
They are removed in this devel version but I can provide the button coloring code not removing the indicator circles.
Just drop me a note.

73 de Martin, DL1RF

**Comment by tomvdb** [comment]
Hi Martin,

Nice work, I've done some tests and definitely feels like its running better on the cpu usage. I need to do some more testing, but I haven't had any issues.

> By the way, do you like the buttons coloring for Stream and Record button in the picture? Are the indicator circles a "shall" for OpenTuner? They are removed in this devel version but I can provide the button coloring code not removing the indicator circles. Just drop me a note.

Yeah, I like it. Im not attached to the circles and the button coloring works better in terms of space, so happy to go ahead with that.

 I did change the properties back again for SR/Modcod for now as I have some other ideas there. We can look later at combining a few but for now I'd like to keep them seperate as the last couple of functionality gets added.

Thanks for all your help, it is much appreciated :)

T

**Pull request merged**
